---
- hosts: all
  tasks:
  - name: Install git and sudo 
    apt:
      name: "{{item}}"
      update_cache: yes
    with_items:
      - git
      - sudo
      - vim
    become: true

  - name: Add user stack
    user:
      name: stack
      shell: /bin/bash
      home: /opt/stack
      system: yes
    become: true

  - name: Add stack user to becomeers
    lineinfile:
      dest: /etc/sudoers.d/stack
      line: "stack ALL=(ALL) NOPASSWD: ALL"    
      create: yes
    become: true

  - name: Clone Devstack
    git: 
      repo: https://git.openstack.org/openstack-dev/devstack
      dest: /devstack
      #version: stable/ocata
      force: yes 
      update: no
      depth: 1
    become: true

  - name: Clone Rally
    git: 
      repo: https://github.com/openstack/rally
      dest: /etc/rally
      force: yes 
      update: no
      depth: 1
    become: true

  - name: Giving /devstack to stack user
    file:
      path: /devstack
      owner: stack
      mode: 0744
      recurse: yes
    become: true

  - name: Patching devstack (host-ip)
    shell: "sed -i 's/HOST_IP=${HOST_IP:-}/ HOST_IP=10.0.2.15/' /devstack/stackrc"
    become: true    

#  #NOTE(acarat): Cockroach doesn't support -T psql option
#  - name: Patching devstack (psql)
#    shell: sed -i 's/psql -h$DATABASE_HOST -U$DATABASE_USER -dtemplate1 -c "DROP DATABASE IF EXISTS $db"/psql -h $DATABASE_HOST -U $DATABASE_USER -c "DROP DATABASE IF EXISTS $db"/' /devstack/lib/databases/postgresql
#    become: true
#    when: cockroach_enabled
#  
#  - name: Patching devstack (createdb)
#    shell: "sed -i 's/createdb -h $DATABASE_HOST -U$DATABASE_USER -l C -T template0 -E utf8 $db/createdb -h $DATABASE_HOST -U $DATABASE_USER -E utf8 $db/' /devstack/lib/databases/postgresql" 
#    become: true
#    when: cockroach_enabled

  - name: Patching devstack (postgresql)
    copy:
      src: patch/postgresql
      dest: /devstack/lib/databases/postgresql
      owner: stack
    become: true
    when: cockroach_enabled

  - name: Patching devstack (keystone)
    copy:
      src: patch/keystone
      dest: /devstack/lib/keystone
      owner: stack
    become: true
    when: cockroach_enabled

  - name: Getting CockroachDB binary
    get_url:
      #url: https://binaries.cockroachdb.com/cockroach-v1.1-alpha.20170629.linux-amd64.tgz
      url: https://binaries.cockroachdb.com/cockroach-v1.0.2.linux-amd64.tgz    
      dest: ~/cockroach.tgz
    when: cockroach_enabled
  

  - name: Unzip CockroachDB binary
    unarchive:
      src: ~/cockroach.tgz
      dest: ~/
    when: cockroach_enabled
  
    
  - name: Install CockroachDB
    command: cp -i cockroach-v1.0.2.linux-amd64/cockroach /usr/local/bin
    args:
      chdir: /home/vagrant  
      creates: /usr/local/bin/cockroach
    become: true
    when: cockroach_enabled
  

  - name: Checking if Cockroach is running
    shell: ps -ef | grep -v grep | grep  "cockroach start" | wc -l
    register: cockroach_is_started
    when: cockroach_enabled
  
   
  #NOTE(acarat): Go with 5432 port (pgsql default) because devstack doesn't let you specify a port
  - name: Start CockroachDB
    command: cockroach start --host=localhost --port=5432 --insecure --background
    args:
      chdir: /opt/stack
    become: true
    become_user: stack
    when: 
      - cockroach_enabled
      - not cockroach_is_started.stdout|int|bool 

  - name: Install CockroachDB sqlalchemy ORM anda custom oslo.db
    pip:
      name: "{{item}}"
    with_items:
      - sqlalchemy==1.1.10
      - cockroachdb
      - git+https://github.com/cara-puce/oslo.db.git@stable/ocata#egg=oslo_db
    become: true
    when: cockroach_enabled

  - name: Configure Devstack in local.conf
    blockinfile:
      path: /devstack/local.conf
      block: |
        [[local|localrc]]
        ADMIN_PASSWORD=admin
        DATABASE_PASSWORD=admin
        RABBIT_PASSWORD=admin
        SERVICE_PASSWORD=admin
        LIBVIRT_TYPE=qemu

        disable_service swift horizon c-api c-sch c-vol dstat g-api g-reg n-api n-cauth n-cond n-cpu n-novnc n-sch placement-api q-agt q-dhcp q-l3 q-meta q-svc
        disable_service mysql
        enable_service postgresql
      create: yes
    become: true    
    become_user: stack


  - name: Add cockroachdb conf in local.conf
    blockinfile:
      path: /devstack/local.conf
      block: |
        [[local|localrc]]
        ADMIN_PASSWORD=admin
        DATABASE_PASSWORD=admin
        RABBIT_PASSWORD=admin
        SERVICE_PASSWORD=admin
        LIBVIRT_TYPE=qemu

        enable_plugin rally https://github.com/openstack/rally master

        disable_service swift horizon c-api c-sch c-vol dstat g-api g-reg n-api n-cauth n-cond n-cpu n-novnc n-sch placement-api q-agt q-dhcp q-l3 q-meta q-svc
        disable_service mysql
        enable_service postgresql

        BASE_SQL_CONN=cockroachdb://root@127.0.0.1
        DATABASE_HOST=127.0.0.1
        DATABASE_USER=root

        [[post-config|$KEYSTONE_CONF]]

        [database]
        connection = cockroachdb://root@127.0.0.1:5432
    become: true    
    become_user: stack
    when: cockroach_enabled

  - name: Clear Devstack
    shell: /devstack/unstack.sh
    become: true
    become_user: stack

  - name: Checking if /tmp/stack-logs exists
    stat:
      path: /tmp/stack-logs
    register: stat_result

  #NOTE(acarat): Hacking around migration because of some conflicts between cockroach and pgsql
  - name: Making migration by hand through a pgdump customized script
    command: psql --host=127.0.0.1 --user=root --dbname=keystone --file=/vagrant/pgdump
    when: 
      - cockroach_enabled
      - stat_result.stat.exists 
    become: true
    become_user: stack

  - name: Adding tempest conf file
    copy:
      src: patch/tempest.conf
      dest: /opt/stack/tempest/etc/tempest.conf
    when: 
      - cockroach_enabled
      - stat_result.stat.exists 
    become: true
    become_user: stack

  - name: Run Devstack
    shell: /devstack/stack.sh &> /tmp/stack-logs
    args:
      executable: /bin/bash
    become: true
    become_user: stack

