---
- hosts: all
  tasks:
  - name: Install git and sudo 
    apt:
      name: "{{item}}"
      update_cache: yes
    with_items:
      - git
      - sudo
    become: true

  - name: Add user stack
    user:
      name: stack
      shell: /bin/bash
      home: /opt/stack
      system: yes
    become: true

  - name: Add stack user to becomeers
    lineinfile:
      dest: /etc/sudoers.d/stack
      line: "stack ALL=(ALL) NOPASSWD: ALL"    
      create: yes
    become: true

  - name: Clone Devstack
    git: 
      repo: https://git.openstack.org/openstack-dev/devstack
      dest: /devstack
      version: stable/ocata
      force: yes 
      update: no
      depth: 1
    become: true

  - name: Giving /devstack to stack user
    file:
      path: /devstack
      owner: stack
      mode: 0744
      recurse: yes
    become: true

  - name: Patching devstack (host-ip)
    shell: "sed -i 's/HOST_IP=${HOST_IP:-}/ HOST_IP=10.0.2.15/' /devstack/stackrc"
    become: true    

  #NOTE(acarat): Cockroach doesn't support -T psql option
  - name: Patching devstack (psql)
    shell: "sed -i 's/createdb -h $DATABASE_HOST -U$DATABASE_USER -l C -T template0 -E utf8 $db/createdb -h $DATABASE_HOST -U$DATABASE_USER -E utf8 $db/' /devstack/lib/databases/postgresql" 
    become: true

  - name: Getting CockroachDB binary
    get_url:
      dest: ~/cockroach-v1.0.2.linux-amd64.tgz
      url: https://binaries.cockroachdb.com/cockroach-v1.0.2.linux-amd64.tgz    
    
  - name: Unzip CockroachDB binary
    unarchive:
      src: ~/cockroach-v1.0.2.linux-amd64.tgz
      dest: ~/
    
  - name: Install CockroachDB
    command: cp -i cockroach-v1.0.2.linux-amd64/cockroach /usr/local/bin
    args:
      chdir: /home/vagrant  
      creates: /usr/local/bin/cockroach
    become: true

  - name: Checking if Cockroach is running
    shell: ps -ef | grep -v grep | grep  "cockroach start" | wc -l
    register: cockroach_is_started
   
  #NOTE(acarat): Go with 5432 port (pgsql default) because devstack doesn't let you specify a port
  - name: Start CockroachDB
    command: cockroach start --host=localhost --port=5432 --insecure --background
    args:
      chdir: /opt/stack
    become: true
    become_user: stack
    when: not cockroach_is_started.stdout|int|bool 

  - name: Install CockroachDB sqlalchemy ORM
    pip:
      name: "{{item}}"
    with_items:
      - sqlalchemy
      - cockroachdb
      - git+https://github.com/cara-puce/oslo.db/oslodb
    become: true
 
  - name: Configure Devstack in local.conf
    blockinfile:
      path: /devstack/local.conf
      block: |
        [[local|localrc]]
        ADMIN_PASSWORD=admin
        DATABASE_PASSWORD=admin
        RABBIT_PASSWORD=admin
        SERVICE_PASSWORD=admin
        LIBVIRT_TYPE=qemu

        DATABASE_HOST=127.0.0.1
        DATABASE_USER=root

        disable_service tempest swift horizon c-api c-sch c-vol dstat g-api g-reg n-api n-cauth n-cond n-cpu n-novnc n-sch placement-api q-agt q-dhcp q-l3 q-meta q-svc
        disable_service mysql
        enable_service postgresql

        [[post-config|$KEYSTONE_CONF]]

        [database]
        connection = cockroachdb://root@127.0.0.1:5432

      create: yes
    become: true    
    become_user: stack

  - name: Clear Devstack
    shell: /devstack/unstack.sh
    become: true
    become_user: stack

  - name: Run Devstack
    shell: /devstack/stack.sh &> /tmp/stack-logs
    args:
      executable: /bin/bash
    become: true
    become_user: stack
